# Generated by Django 5.2.4 on 2025-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('superadmin', 'SuperAdmin')], default='user', max_length=20),
        ),
    ]
