# Generated by Django 5.2.4 on 2025-07-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('year_exp', models.PositiveIntegerField()),
                ('services', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Headings',
                'ordering': ['-rating'],
            },
        ),
    ]
