# Generated by Django 5.2.4 on 2025-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingmodel',
            options={'ordering': ['-rating'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='happy_clients',
            field=models.CharField(max_length=10),
        ),
    ]
