# Generated by Django 5.2.4 on 2025-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatments', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('descriptions', models.CharField(max_length=255)),
                ('included', models.JSONField()),
                ('is_popular', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-price'],
            },
        ),
    ]
