# Generated by Django 5.2.4 on 2025-07-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertmodel',
            old_name='certification',
            new_name='certifications',
        ),
        migrations.RenameField(
            model_name='expertmodel',
            old_name='descriptions',
            new_name='description',
        ),
    ]
